### ISSUE TITLE
Pattern bug dispersed throughout this file. 

### ISSUE THREAD

**Issue by utekai** [gleblebedev/UrhoSharpToolkit#3]
https://github.com/gleblebedev/UrhoSharpToolkit/blob/master/src/UrhoSharp.Interfaces/InputAdapter.cs

System.InvalidOperationException: 'Subscription.Unsubscribe was invoked after Application.Stop'

[Saw this at this line.](https://github.com/gleblebedev/UrhoSharpToolkit/blob/4b1c56e91f10ccdc6c10dc496aadc5492cbc1a88/src/UrhoSharp.Interfaces/InputAdapter.cs#L399)

[Triggered by this call.](https://github.com/gleblebedev/UrhoSharpToolkit/blob/4b1c56e91f10ccdc6c10dc496aadc5492cbc1a88/src/UrhoSharp.Pages/AbstractNavigationApp.cs#L40)

[When running this and x-ed out of the program.](https://github.com/gleblebedev/UrhoSharpToolkit/blob/4b1c56e91f10ccdc6c10dc496aadc5492cbc1a88/src/UrhoSharp.Toolkit.DesktopDemo/Program.cs#L22)

**Comment by gleblebedev** [comment]
This happens when you close the app. Should first dispose the proxy and then destroy the app.
